pages:
  script:
  - line=$(cat CMakeLists.txt | grep "project(.*)" -o); tmp=${line:8}; proj_name=${tmp:0:${#tmp}-1}; # parse the project name
  - sed -i 's/\(PROJECT_NAME\s*=\s*\)\".*\"/\1\"'$proj_name'\"/g' Doxyfile Doxyfile; # rename the project in the Doxyfile
  - doxygen Doxyfile # generate the documentation
  - rm -rf ~/public_artifacts/doc/$proj_name # remove old documentation folder of this project
  - mkdir -p ~/public_artifacts/doc # if the doc folder does not exist, create it
  - mv -f doc/html ~/public_artifacts/doc/$proj_name # finally move the generated documentation to the synced folder
  artifacts:
    paths:
    - doc
  only:
  - master
